### ISSUE TITLE
Add "Download Setlist as OpenLP File" Feature to Download Menu

### ISSUE THREAD

**Issue by Gui-k** [devmount/SongDrive#216] opened 2024-06-02 16:02 UTC
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I need to manually convert setlists to OpenLP files to use them in OpenLP ;-)

**Describe the solution you'd like**
I would like a "download setlist as OpenLP file" feature. It would be in the download menu, complementing the two existing ones (download list as PDF and download sheet as PDF). The downloaded file needs to contain each of the songs part of the playlist (exactly as if you save a service in OpenLP, the .osz file contains all the songs). That way, when you open the service in OpenLP, even if the songs don't exist in the database, it will import them and add them to the OpenLP database.

**Describe alternatives you've considered**

1. Keep doing it manually.

2. Use the OpenLP API (which I am not sure has the ability yet to create services) (https://gitlab.com/openlp/wiki/-/wikis/Development/Core_API_Framework).

Merci :-)

**Comment by devmount** [comment] 2024-06-05 11:37
After [some digging](https://discuss.openlp.org/d/2545-information-about-osz-file) and reverse engineering on OpenLP service file format `.osz`: It's just a simple ZIP container holding one file `service_data.osj` which is in JSON format. Since I didn't find any documentation on this, let's just take a look at it and reproduce it accordingly.

The structure seems to be like this:

```json
[
  {
    "openlp_core": {
      "lite-service": false,
      "service-theme": null,
      "openlp-servicefile-version": 3
    }
  },
  {
    "serviceitem": {
      "header": {
        "name": "songs",
        "plugin": "songs",
        "theme": null,
        "title": "...",
        "footer": [],
        "type": 1,
        "audit": [],
        "notes": "",
        "from_plugin": false,
        "capabilities": [],
        "search": "",
        "data": {
          "title": "title@subtitle",
          "alternate_title": "...",
          "authors": "...",
          "ccli_number": "",
          "copyright": ""
        },
        "xml_version": "Complete song text in XML song format",
        "auto_play_slides_once": false,
        "auto_play_slides_loop": false,
        "timed_slide_interval": 0,
        "start_time": 0,
        "end_time": 0,
        "media_length": 0,
        "background_audio": [],
        "theme_overwritten": false,
        "will_auto_start": false,
        "processor": null,
        "metadata": [],
        "sha256_file_hash": null,
        "stored_filename": null
      },
      "data": [
        {
          "title": "...",
          "raw_slide": "Raw text song text for this part (e.g. first verse)",
          "verseTag": "V1"
        },
        {
          "title": "...",
          "raw_slide": "Raw text song text for this part (e.g. first chorus)",
          "verseTag": "C1"
        }
      ]
    }
  }
]
```

Should be doable to create `.osz` files right from SongDrive. I did some tests and it looks like we can even skip the generation of the `xml_version`, which saves a lot of time. We simply have to create a default header object and a data array holding all songparts with title, raw text and verse tag. That's it.

Edit: In fact, the `xml_version` part was needed after all, but that part was already implemented in SongDrive.

**Comment by devmount** [comment] 2024-06-05 15:07
@Gui-k Done. Will be part of the next release. Let me know if there are any issues when importing to OpenLP.

**Comment by devmount** [comment] 2024-06-05 15:20
I found one more issue and will fix that later. Reopening this.

**Closed as completed** 2024-06-05 20:51 UTC
Labels: feature

**Comment by devmount** [comment] 2024-06-05 20:53
Alright, should be fixed now.

**Comment by Gui-k** [comment] 2024-06-06 05:48
Hey @devmount,

Wahou, I am impressed, thank you for the express delivery 👍

I did a few imports/exports, and it seems to work well. The only issue, but here we are talking "data governance/management," is that if the songs exported are already in the local OpenLP DB and are not exactly 1:1 (title, author, structure, etc.), it's going to create a duplicate. Most of our songs are already from SongSelect, which I assume is what we are exporting, so it shouldn't be a big issue.

As we import songs gradually, keeping an eye on that and eventually deleting the "other" version would be a good practice. This will need to be communicated to the team members.

But well, fantastic work, thank you so much! ❤️

**Comment by devmount** [comment] 2024-06-06 06:49
My pleasure. Yes, in my tests, even if the song was 1:1 exactly the same (I imported the same service file multiple times), OpenLP would still duplicate some (!) of the songs 🤷🏻 I don't know which data is used by OpenLP to identify a song (it creates an internal song id by the songs xml data, but that should stay the same), so I might not be able to solve this.

**Comment by Gui-k** [comment] 2024-06-06 16:45
Ah! I found an easy solution ;-)

By default, "Import missing songs from Service files" is checked. If we uncheck it, there will be no duplicates.
New songs won't be saved in the database, but to be honest, I don't think it's an issue. The songs in the services are likely stored in session memory. When you close OpenLP, they are gone. I thought it was possible to save them by right-clicking on the song, then clicking on "Edit" and "Save," but it only modifies the temporary song. This could probably be easily implemented on the OpenLP side.

![image](https://github.com/devmount/SongDrive/assets/12269481/75748ca8-f5d7-47e8-ba5a-fb434c8b1e59)

**Comment by devmount** [comment] 2024-06-06 19:55
Ah thank you for this addition ad clarification! Yes this setting should be sufficient to solve the duplicate song issue.
